In [2]:
import gensim
from gensim import corpora
from google.colab import drive

In [3]:
drive.mount('/content/drive')

Mounted at /content/drive

Reading file from drive

In [5]:
import pandas as pd
with open('/content/drive/MyDrive/Springboard/capstone3/mc160.dev.txt') as f:
    contents = f.read()
    
#print(contents)

Converting string into dataframe

In [6]:
list1 = list(contents.split("***************************************************"))
#print(len(list1))
#print(list1)
print(len(list1))
str1 = ""
#print(list1[1][0:82])
#print(list1[2][0:82])
for i in range(1,len(list1)):
  #print((list1[i][0:82]))
  str1 = list1[i][0:82]
  #print("inside loop")
  #print(str1)
  list1[i]=list1[i].replace(str1,'')
print(list1[2])

31

Sally had a very exciting summer vacation. She went to summer camp for the first time. She
made friends with a girl named Tina. They shared a bunk bed in their cabin. Sally's
favorite activity was walking in the woods because she enjoyed nature. Tina liked arts and
crafts. Together, they made some art using leaves they found in the woods. Even after she
fell in the water, Sally still enjoyed canoeing. She was sad when the camp was over, but
promised to keep in touch with her new friend.

Sally went to the beach with her family in the summer as well. She loves the beach. Sally
collected shells and mailed some to her friend, Tina, so she could make some arts and
crafts with them. Sally liked fishing with her brothers, cooking on the grill with her dad,
and swimming in the ocean with her mother.

The summer was fun, but Sally was very excited to go back to school. She missed her
friends and teachers. She was excited to tell them about her summer vacation.

1: multiple: Who went to the beach with Sally?
 A) her sisters
 B) Tina
*C) her brothers, mother, and father
 D) herself

2: multiple: What did Sally promise to do?
 A) Learn to ride a bike.
 B) Go to a baseball game.
 C) Go back to the beach.
*D) Keep in touch with her new friend, Tina.

3: one: Why does Sally like walking in the woods?
 A) She likes to climb trees.
 B) She likes to play hide and go seek.
 C) She likes to swim.
*D) She likes nature.

4: multiple: What did Sally do this summer?
*A) She went to summer camp and the beach.
 B) She went to Paris.
 C) She went to a baseball game.
 D) She went to summer school.

In [7]:
df = pd.DataFrame (list1)
df.rename(columns={0: 'para'}, inplace=True)
df = df.iloc[1: , :]
#df.head()

In [8]:
location_df = df['para'].apply(lambda x: pd.Series(x.split('1')))
location_df.rename(columns={0: 'Paragraph',1:'multiple_choice'}, inplace=True)
#location_df.head(2)

In [9]:
location_df['multiple_choice'].dtypes

dtype('O')

In [10]:
df1 = location_df['multiple_choice'].apply(lambda x: pd.Series(str(x).split('2:')))
df1.rename(columns={0: 'Q1',1:'rest'}, inplace=True)
#df1.head()

In [11]:
df2 = df1['rest'].apply(lambda x: pd.Series(str(x).split('3:')))
df2.rename(columns={0: 'Q2',1:'rest'}, inplace=True)
#df2.head(5)

In [12]:
df3 = df2['rest'].apply(lambda x: pd.Series(str(x).split('4:')))
df3.rename(columns={0: 'Q3',1:'Q4'}, inplace=True)
#df3.head(5)

# Final DF

In [13]:
result_df = pd.concat([location_df['Paragraph'], df1['Q1'],df2['Q2'],df3], axis=1)
result_df.head()

,Paragraph,Q1,Q2,Q3,Q4
1,\n\nIt was Jessie Bear's birthday. She was hav...,: one: Who was having a birthday?\n*A) Jessie ...,multiple: Who didn't come to the party?\n A) ...,multiple: How did Jessie get ready for the pa...,one: How many friends came to Jessie's party?...
2,\nSally had a very exciting summer vacation. S...,: multiple: Who went to the beach with Sally?\...,multiple: What did Sally promise to do?\n A) ...,one: Why does Sally like walking in the woods...,multiple: What did Sally do this summer?\n*A)...
3,\nTodd lived in a town outside the city . Unli...,: multiple: Where did Todd visit?\n*A) The cit...,multiple: What did Todd say when he got home ...,one: Where does Todd live?\n A) The city\n B)...,multiple: What did Todd see when he got to th...
4,\n\nGreta ran to the corner with her older bro...,: multiple: What did the driver of the ice cre...,multiple: What did the children do when they ...,multiple: What did Tony and Greta get from th...,multiple: What did Greta and Tony do after th...
5,"\n\nMy parents, Kelly and Kelley, said that it...",: one: What was my brother's name?\n A) Kelly\...,one: Where did we go?\n A) Hood River Castle\...,multiple: What did the castle have?\n A) A ba...,multiple: What did we do at the castle?\n A) ...

# Remove Unicode Characters

# Stop words Removal

In [14]:
pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.7/dist-packages (3.2.5)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from nltk) (1.15.0)

In [15]:
import nltk
nltk.download('all')
nltk.download('stopwords')

[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/biocreative_ppi.zip.
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/bllip_wsj_no_aux.zip.
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/book_grammars.zip.
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown.zip.
[nltk_data]    | Downloading package brown_tei to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown_tei.zip.
[nltk_data]    | Downloading package cess_cat to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_cat.zip.
[nltk_data]    | Downloading package cess_esp to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_esp.zip.
[nltk_data]    | Downloading package chat80 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/chat80.zip.
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/city_database.zip.
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cmudict.zip.
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/comparative_sentences.zip.
[nltk_data]    | Downloading package comtrans to /root/nltk_data...
[nltk_data]    | Downloading package conll2000 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2000.zip.
[nltk_data]    | Downloading package conll2002 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2002.zip.
[nltk_data]    | Downloading package conll2007 to /root/nltk_data...
[nltk_data]    | Downloading package crubadan to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/crubadan.zip.
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/dependency_treebank.zip.
[nltk_data]    | Downloading package dolch to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/dolch.zip.
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/europarl_raw.zip.
[nltk_data]    | Downloading package extended_omw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/extended_omw.zip.
[nltk_data]    | Downloading package floresta to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/floresta.zip.
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/framenet_v15.zip.
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/framenet_v17.zip.
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gazetteers.zip.
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/genesis.zip.
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gutenberg.zip.
[nltk_data]    | Downloading package ieer to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ieer.zip.
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/inaugural.zip.
[nltk_data]    | Downloading package indian to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/indian.zip.
[nltk_data]    | Downloading package jeita to /root/nltk_data...
[nltk_data]    | Downloading package kimmo to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/kimmo.zip.
[nltk_data]    | Downloading package knbc to /root/nltk_data...
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/large_grammars.zip.
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/lin_thesaurus.zip.
[nltk_data]    | Downloading package mac_morpho to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/mac_morpho.zip.
[nltk_data]    | Downloading package machado to /root/nltk_data...
[nltk_data]    | Downloading package masc_tagged to /root/nltk_data...
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/maxent_treebank_pos_tagger.zip.
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/moses_sample.zip.
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/movie_reviews.zip.
[nltk_data]    | Downloading package mte_teip5 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/mte_teip5.zip.
[nltk_data]    | Downloading package mwa_ppdb to /root/nltk_data...
[nltk_data]    |   Unzipping misc/mwa_ppdb.zip.
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/names.zip.
[nltk_data]    | Downloading package nombank.1.0 to /root/nltk_data...
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/nonbreaking_prefixes.zip.
[nltk_data]    | Downloading package nps_chat to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/nps_chat.zip.
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/omw.zip.
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/omw-1.4.zip.
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/opinion_lexicon.zip.
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package paradigms to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/paradigms.zip.
[nltk_data]    | Downloading package pe08 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pe08.zip.
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping misc/perluniprops.zip.
[nltk_data]    | Downloading package pil to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pil.zip.
[nltk_data]    | Downloading package pl196x to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pl196x.zip.
[nltk_data]    | Downloading package porter_test to /root/nltk_data...
[nltk_data]    |   Unzipping stemmers/porter_test.zip.
[nltk_data]    | Downloading package ppattach to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ppattach.zip.
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/problem_reports.zip.
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/product_reviews_1.zip.
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/product_reviews_2.zip.
[nltk_data]    | Downloading package propbank to /root/nltk_data...
[nltk_data]    | Downloading package pros_cons to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pros_cons.zip.
[nltk_data]    | Downloading package ptb to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ptb.zip.
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Unzipping tokenizers/punkt.zip.
[nltk_data]    | Downloading package qc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/qc.zip.
[nltk_data]    | Downloading package reuters to /root/nltk_data...
[nltk_data]    | Downloading package rslp to /root/nltk_data...
[nltk_data]    |   Unzipping stemmers/rslp.zip.
[nltk_data]    | Downloading package rte to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/rte.zip.
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/sample_grammars.zip.
[nltk_data]    | Downloading package semcor to /root/nltk_data...
[nltk_data]    | Downloading package senseval to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/senseval.zip.
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sentence_polarity.zip.
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sentiwordnet.zip.
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/shakespeare.zip.
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sinica_treebank.zip.
[nltk_data]    | Downloading package smultron to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/smultron.zip.
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/spanish_grammars.zip.
[nltk_data]    | Downloading package state_union to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/state_union.zip.
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/stopwords.zip.
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/subjectivity.zip.
[nltk_data]    | Downloading package swadesh to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/swadesh.zip.
[nltk_data]    | Downloading package switchboard to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/switchboard.zip.
[nltk_data]    | Downloading package tagsets to /root/nltk_data...
[nltk_data]    |   Unzipping help/tagsets.zip.
[nltk_data]    | Downloading package timit to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/timit.zip.
[nltk_data]    | Downloading package toolbox to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/toolbox.zip.
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/treebank.zip.
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/twitter_samples.zip.
[nltk_data]    | Downloading package udhr to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/udhr.zip.
[nltk_data]    | Downloading package udhr2 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/udhr2.zip.
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/unicode_samples.zip.
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/universal_tagset.zip.
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package verbnet to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/verbnet.zip.
[nltk_data]    | Downloading package verbnet3 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/verbnet3.zip.
[nltk_data]    | Downloading package webtext to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/webtext.zip.
[nltk_data]    | Downloading package wmt15_eval to /root/nltk_data...
[nltk_data]    |   Unzipping models/wmt15_eval.zip.
[nltk_data]    | Downloading package word2vec_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/word2vec_sample.zip.
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet.zip.
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet2021.zip.
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet31.zip.
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet_ic.zip.
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/words.zip.
[nltk_data]    | Downloading package ycoe to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ycoe.zip.
[nltk_data]    |
[nltk_data]  Done downloading collection all
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [16]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

sw_nltk = stopwords.words('english')
new_list = ['myself','ourselves','yourself', 'yourselves','himself','herself','itself']
for i in new_list:
  sw_nltk.remove(i)
print(sw_nltk)

# remove the sublist with herself,yourself and all

['i', 'me', 'my', 'we', 'our', 'ours', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'he', 'him', 'his', 'she', "she's", 'her', 'hers', 'it', "it's", 'its', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

In [17]:
result_df1 =result_df
result_df['paragraph_without_stopwords'] = result_df['Paragraph'].apply(lambda x: ' '.join([word for word in x.split() if word not in (sw_nltk)]))
result_df['Q1_without_stopwords'] = result_df['Q1'].apply(lambda x: ' '.join([word for word in x.split() if word not in (sw_nltk)]))
result_df['Q2_without_stopwords'] = result_df['Q2'].apply(lambda x: ' '.join([word for word in x.split() if word not in (sw_nltk)]))
result_df['Q3_without_stopwords'] = result_df['Q3'].apply(lambda x: ' '.join([word for word in x.split() if word not in (sw_nltk)]))
result_df['Q4_without_stopwords'] = result_df['Q4'].apply(lambda x: ' '.join([word for word in str(x).split() if word not in (sw_nltk)]))
#print(word_tokens)
result_df.head()
#print(filtered_sentence)
# remove one and multiple
# isolate question and answers
# extract question new column
#Q1_A,Q1_B,Q1_C,Q1_D separately
#lemmatize or stemming paragraph, question and answers(4)

,Paragraph,Q1,Q2,Q3,Q4,paragraph_without_stopwords,Q1_without_stopwords,Q2_without_stopwords,Q3_without_stopwords,Q4_without_stopwords
1,\n\nIt was Jessie Bear's birthday. She was hav...,: one: Who was having a birthday?\n*A) Jessie ...,multiple: Who didn't come to the party?\n A) ...,multiple: How did Jessie get ready for the pa...,one: How many friends came to Jessie's party?...,It Jessie Bear's birthday. She party. She aske...,: one: Who birthday? *A) Jessie Bear B) one C)...,multiple: Who come party? A) Lion B) Tiger *C)...,multiple: How Jessie get ready party? A) made ...,one: How many friends came Jessie's party? A) ...
2,\nSally had a very exciting summer vacation. S...,: multiple: Who went to the beach with Sally?\...,multiple: What did Sally promise to do?\n A) ...,one: Why does Sally like walking in the woods...,multiple: What did Sally do this summer?\n*A)...,Sally exciting summer vacation. She went summe...,: multiple: Who went beach Sally? A) sisters B...,multiple: What Sally promise do? A) Learn ride...,one: Why Sally like walking woods? A) She like...,multiple: What Sally summer? *A) She went summ...
3,\nTodd lived in a town outside the city . Unli...,: multiple: Where did Todd visit?\n*A) The cit...,multiple: What did Todd say when he got home ...,one: Where does Todd live?\n A) The city\n B)...,multiple: What did Todd see when he got to th...,Todd lived town outside city . Unlike city tow...,: multiple: Where Todd visit? *A) The city B) ...,multiple: What Todd say got home city? A) Ther...,one: Where Todd live? A) The city B) mom C) da...,multiple: What Todd see got city? A) lots anim...
4,\n\nGreta ran to the corner with her older bro...,: multiple: What did the driver of the ice cre...,multiple: What did the children do when they ...,multiple: What did Tony and Greta get from th...,multiple: What did Greta and Tony do after th...,Greta ran corner older brother Tony. He money ...,: multiple: What driver ice cream truck Greta ...,multiple: What children saw ice cream truck dr...,multiple: What Tony Greta get iced cream truck...,multiple: What Greta Tony got ice cream? A) Th...
5,"\n\nMy parents, Kelly and Kelley, said that it...",: one: What was my brother's name?\n A) Kelly\...,one: Where did we go?\n A) Hood River Castle\...,multiple: What did the castle have?\n A) A ba...,multiple: What did we do at the castle?\n A) ...,"My parents, Kelly Kelley, said time year take ...",: one: What brother's name? A) Kelly *B) Kelse...,one: Where go? A) Hood River Castle *B) Elk Ri...,multiple: What castle have? A) A ball room *B)...,multiple: What castle? A) Played ball B) Fishe...

In [18]:
result_df1.head()

,Paragraph,Q1,Q2,Q3,Q4,paragraph_without_stopwords,Q1_without_stopwords,Q2_without_stopwords,Q3_without_stopwords,Q4_without_stopwords
1,\n\nIt was Jessie Bear's birthday. She was hav...,: one: Who was having a birthday?\n*A) Jessie ...,multiple: Who didn't come to the party?\n A) ...,multiple: How did Jessie get ready for the pa...,one: How many friends came to Jessie's party?...,It Jessie Bear's birthday. She party. She aske...,: one: Who birthday? *A) Jessie Bear B) one C)...,multiple: Who come party? A) Lion B) Tiger *C)...,multiple: How Jessie get ready party? A) made ...,one: How many friends came Jessie's party? A) ...
2,\nSally had a very exciting summer vacation. S...,: multiple: Who went to the beach with Sally?\...,multiple: What did Sally promise to do?\n A) ...,one: Why does Sally like walking in the woods...,multiple: What did Sally do this summer?\n*A)...,Sally exciting summer vacation. She went summe...,: multiple: Who went beach Sally? A) sisters B...,multiple: What Sally promise do? A) Learn ride...,one: Why Sally like walking woods? A) She like...,multiple: What Sally summer? *A) She went summ...
3,\nTodd lived in a town outside the city . Unli...,: multiple: Where did Todd visit?\n*A) The cit...,multiple: What did Todd say when he got home ...,one: Where does Todd live?\n A) The city\n B)...,multiple: What did Todd see when he got to th...,Todd lived town outside city . Unlike city tow...,: multiple: Where Todd visit? *A) The city B) ...,multiple: What Todd say got home city? A) Ther...,one: Where Todd live? A) The city B) mom C) da...,multiple: What Todd see got city? A) lots anim...
4,\n\nGreta ran to the corner with her older bro...,: multiple: What did the driver of the ice cre...,multiple: What did the children do when they ...,multiple: What did Tony and Greta get from th...,multiple: What did Greta and Tony do after th...,Greta ran corner older brother Tony. He money ...,: multiple: What driver ice cream truck Greta ...,multiple: What children saw ice cream truck dr...,multiple: What Tony Greta get iced cream truck...,multiple: What Greta Tony got ice cream? A) Th...
5,"\n\nMy parents, Kelly and Kelley, said that it...",: one: What was my brother's name?\n A) Kelly\...,one: Where did we go?\n A) Hood River Castle\...,multiple: What did the castle have?\n A) A ba...,multiple: What did we do at the castle?\n A) ...,"My parents, Kelly Kelley, said time year take ...",: one: What brother's name? A) Kelly *B) Kelse...,one: Where go? A) Hood River Castle *B) Elk Ri...,multiple: What castle have? A) A ball room *B)...,multiple: What castle? A) Played ball B) Fishe...

In [44]:
result_df['Q1_without_stopwords']= result_df['Q1_without_stopwords'].str.replace('*', '')
result_df['Q1_without_stopwords']= result_df['Q1_without_stopwords'].str.replace('?', '')
#result_df['Q1_without_stopwords']= result_df['Q1_without_stopwords'].str.replace(':', '')
result_df['Q1_without_stopwords']= result_df['Q1_without_stopwords'].str.replace('multiple:', '')
result_df['Q1_without_stopwords']= result_df['Q1_without_stopwords'].str.replace('one:', '')
result_df['Q1_without_stopwords']= result_df['Q1_without_stopwords'].str.replace(':', '')
result_df['Q1_without_stopwords'] = result_df['Q1_without_stopwords'].astype(str)
#final_df.head()
result_df.head()
#result_df.dtypes

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

,Paragraph,Q1,Q2,Q3,Q4,paragraph_without_stopwords,Q1_without_stopwords,Q2_without_stopwords,Q3_without_stopwords,Q4_without_stopwords
1,\n\nIt was Jessie Bear's birthday. She was hav...,: one: Who was having a birthday?\n*A) Jessie ...,multiple: Who didn't come to the party?\n A) ...,multiple: How did Jessie get ready for the pa...,one: How many friends came to Jessie's party?...,It Jessie Bear's birthday. She party. She aske...,Who birthday A) Jessie Bear B) one C) Lion D...,multiple: Who come party? A) Lion B) Tiger *C)...,multiple: How Jessie get ready party? A) made ...,one: How many friends came Jessie's party? A) ...
2,\nSally had a very exciting summer vacation. S...,: multiple: Who went to the beach with Sally?\...,multiple: What did Sally promise to do?\n A) ...,one: Why does Sally like walking in the woods...,multiple: What did Sally do this summer?\n*A)...,Sally exciting summer vacation. She went summe...,Who went beach Sally A) sisters B) Tina C) b...,multiple: What Sally promise do? A) Learn ride...,one: Why Sally like walking woods? A) She like...,multiple: What Sally summer? *A) She went summ...
3,\nTodd lived in a town outside the city . Unli...,: multiple: Where did Todd visit?\n*A) The cit...,multiple: What did Todd say when he got home ...,one: Where does Todd live?\n A) The city\n B)...,multiple: What did Todd see when he got to th...,Todd lived town outside city . Unlike city tow...,Where Todd visit A) The city B) His mom C) T...,multiple: What Todd say got home city? A) Ther...,one: Where Todd live? A) The city B) mom C) da...,multiple: What Todd see got city? A) lots anim...
4,\n\nGreta ran to the corner with her older bro...,: multiple: What did the driver of the ice cre...,multiple: What did the children do when they ...,multiple: What did Tony and Greta get from th...,multiple: What did Greta and Tony do after th...,Greta ran corner older brother Tony. He money ...,What driver ice cream truck Greta Tony got c...,multiple: What children saw ice cream truck dr...,multiple: What Tony Greta get iced cream truck...,multiple: What Greta Tony got ice cream? A) Th...
5,"\n\nMy parents, Kelly and Kelley, said that it...",: one: What was my brother's name?\n A) Kelly\...,one: Where did we go?\n A) Hood River Castle\...,multiple: What did the castle have?\n A) A ba...,multiple: What did we do at the castle?\n A) ...,"My parents, Kelly Kelley, said time year take ...",What brother's name A) Kelly B) Kelsey C) Ca...,one: Where go? A) Hood River Castle *B) Elk Ri...,multiple: What castle have? A) A ball room *B)...,multiple: What castle? A) Played ball B) Fishe...

In [45]:
df1_Q1 = result_df['Q1_without_stopwords'].apply(lambda x: pd.Series(str(x).split('A)')))
df1_Q1.rename(columns={0: 'Q1',1:'rest'}, inplace=True)
#df1_Q1.head()

In [46]:
df1_Q1_A = df1_Q1['rest'].apply(lambda x: pd.Series(str(x).split('B)')))
df1_Q1_A.rename(columns={0: 'Q1_A',1:'rest'}, inplace=True)
#df1_Q1_A.head()

In [47]:
df1_Q1_B = df1_Q1_A['rest'].apply(lambda x: pd.Series(str(x).split('C)')))
df1_Q1_B.rename(columns={0: 'Q1_B',1:'rest'}, inplace=True)
#df1_Q1_B.head()

In [48]:
df1_Q1_C = df1_Q1_B['rest'].apply(lambda x: pd.Series(str(x).split('D)')))
df1_Q1_C.rename(columns={0: 'Q1_C',1:'Q1_D'}, inplace=True)
#df1_Q1_C.head()

In [75]:
final_df_Q1 = pd.concat([result_df['paragraph_without_stopwords'],df1_Q1['Q1'], df1_Q1_A['Q1_A'],df1_Q1_B['Q1_B'],df1_Q1_C], axis=1)


#result_df['Q1_without_stopwords']= result_df['Q1_without_stopwords'].replace(to_replace = ['one:','multiple:'],value ='', inplace = True)

final_df_Q1.head()

,paragraph_without_stopwords,Q1,Q1_A,Q1_B,Q1_C,Q1_D
1,It Jessie Bear's birthday. She party. She aske...,Who birthday,Jessie Bear,one,Lion,Tiger
2,Sally exciting summer vacation. She went summe...,Who went beach Sally,sisters,Tina,"brothers, mother, father",herself
3,Todd lived town outside city . Unlike city tow...,Where Todd visit,The city,His mom,The town,The animals
4,Greta ran corner older brother Tony. He money ...,What driver ice cream truck Greta Tony got c...,He started pulling away curb.,He played truck's jingle.,He stayed parked curb.,He almost got snow cone.
5,"My parents, Kelly Kelley, said time year take ...",What brother's name,Kelly,Kelsey,Caden,Colby

In [73]:
#final_df_Q1['Q1_D'] = final_df_Q1['Q1_D'].astype(str)
#final_df_Q1['paragraph_tokenized']= final_df_Q1['paragraph_without_stopwords'].apply(word_tokenize)
#final_df_Q1['Q1_tokenize'] = final_df_Q1['Q1'].apply(word_tokenize)
#final_df_Q1['Q1_A_tokenize'] = final_df_Q1['Q1_A'].apply(word_tokenize)
#final_df_Q1['Q1_B_tokenize'] = final_df_Q1['Q1_B'].apply(word_tokenize)
#final_df_Q1['Q1_C_tokenize'] = final_df_Q1['Q1_C'].apply(word_tokenize)
#final_df_Q1['Q1_D_tokenize'] = final_df_Q1['Q1_D'].apply(word_tokenize)
#final_df_Q1.head()

# Stemming

In [51]:
from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer
from nltk.stem import WordNetLemmatizer

# removing special characters

# Lemmatization

In [76]:
##remove puncuation
import string
punc = string.punctuation

#final_df_Q1['Q1_tokenize'] = final_df_Q1['Q1_tokenize'].apply(lambda x: [word for word in x if word not in punc])
#final_df_Q1['Q1_A_tokenize'] = final_df_Q1['Q1_A_tokenize'].apply(lambda x: [word for word in x if word not in punc])
#final_df_Q1['Q1_B_tokenize'] = final_df_Q1['Q1_B_tokenize'].apply(lambda x: [word for word in x if word not in punc])
#final_df_Q1['Q1_C_tokenize'] = final_df_Q1['Q1_C_tokenize'].apply(lambda x: [word for word in x if word not in punc])
#final_df_Q1['Q1_D_tokenize'] = final_df_Q1['Q1_D_tokenize'].apply(lambda x: [word for word in x if word not in punc])
#final_df_Q1.head()

In [77]:
wnl = WordNetLemmatizer()
#final_df_Q1['paragraph_lemmatized'] = final_df_Q1['Q1_tokenize'].apply(lambda x: [wnl.lemmatize(word) for word in x])
#final_df_Q1['Q1_lemmatized'] = final_df_Q1['Q1_tokenize'].apply(lambda x: [wnl.lemmatize(word) for word in x])
#final_df_Q1['Q1_A_lemmatized'] = final_df_Q1['Q1_A_tokenize'].apply(lambda x: [wnl.lemmatize(word) for word in x])
#final_df_Q1['Q1_B_lemmatized'] = final_df_Q1['Q1_B_tokenize'].apply(lambda x: [wnl.lemmatize(word) for word in x])
#final_df_Q1['Q1_C_lemmatized'] = final_df_Q1['Q1_C_tokenize'].apply(lambda x: [wnl.lemmatize(word) for word in x])
final_df_Q1.head()

,paragraph_without_stopwords,Q1,Q1_A,Q1_B,Q1_C,Q1_D
1,It Jessie Bear's birthday. She party. She aske...,Who birthday,Jessie Bear,one,Lion,Tiger
2,Sally exciting summer vacation. She went summe...,Who went beach Sally,sisters,Tina,"brothers, mother, father",herself
3,Todd lived town outside city . Unlike city tow...,Where Todd visit,The city,His mom,The town,The animals
4,Greta ran corner older brother Tony. He money ...,What driver ice cream truck Greta Tony got c...,He started pulling away curb.,He played truck's jingle.,He stayed parked curb.,He almost got snow cone.
5,"My parents, Kelly Kelley, said time year take ...",What brother's name,Kelly,Kelsey,Caden,Colby

In [78]:
# get local paragraph example
loc_para = final_df_Q1.iloc[0,0]
print(loc_para)

It Jessie Bear's birthday. She party. She asked two best friends come party. She made big cake, hung balloons. Soon friend Lion came over. Then friend Tiger came over. Lion Tiger brought presents them. Jessie hugged friends. She asked would like cake. Yes! said Lion. Yes yes! said Tiger. Jessie cut cake, ate together. Then Jessie opened presents. She got new jump rope fun game. She asked Lion Tiger play game her. The friends played played. They good time. Soon time party over. Lion Tiger hugged Jessie said goodbye her. Thanks great birthday! Jessie Bear told two best friends.

In [ ]:
#simplest approach transform paragraph to TFIDF (for each sentence) result in additional column
#NER with stopwords will be more effective
#TFIDF for question also
#cosine similarity or some other similarity between question TFIDF with each sentence TFIDF

In [79]:
# get local Question example
loc_Q = final_df_Q1.iloc[0,1]
print(loc_Q)

  Who birthday

In [80]:
# Get list of sentences belowing to one paragraph
loc_para_split = loc_para.split('. ')
loc_para_split

["It Jessie Bear's birthday",
 'She party',
 'She asked two best friends come party',
 'She made big cake, hung balloons',
 'Soon friend Lion came over',
 'Then friend Tiger came over',
 'Lion Tiger brought presents them',
 'Jessie hugged friends',
 'She asked would like cake',
 'Yes! said Lion',
 'Yes yes! said Tiger',
 'Jessie cut cake, ate together',
 'Then Jessie opened presents',
 'She got new jump rope fun game',
 'She asked Lion Tiger play game her',
 'The friends played played',
 'They good time',
 'Soon time party over',
 'Lion Tiger hugged Jessie said goodbye her',
 'Thanks great birthday! Jessie Bear told two best friends.']

Match with each sentence with question
each paragraph as a list of sentences apply TFIDF list of vectors
apply it on the question
cosine similarity between each sentence with Q1

In [ ]:
pip install scikit-learn

In [81]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(smooth_idf=True,use_idf=True)
vect_result = vectorizer.fit_transform(loc_para_split)
loc_para_tfidf = pd.DataFrame(vect_result.toarray(), columns=vectorizer.get_feature_names())
loc_para_tfidf.head(3)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,asked,ate,balloons,bear,best,big,birthday,brought,cake,came,...,them,then,they,tiger,time,together,told,two,would,yes
0,0.000000,0.0,0.0,0.512874,0.000000,0.0,0.512874,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
1,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
2,0.364948,0.0,0.0,0.000000,0.404443,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.404443,0.0,0.0

In [82]:
# Apply to Question
vect_result = vectorizer.transform([loc_Q])
loc_Q_tfidf = pd.DataFrame(vect_result.toarray(), columns=vectorizer.get_feature_names())
loc_Q_tfidf.head(3)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,asked,ate,balloons,bear,best,big,birthday,brought,cake,came,...,them,then,they,tiger,time,together,told,two,would,yes
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [83]:
# Compute cosine similarity between one sentence and the Question
# This is an example
import numpy as np
from numpy.linalg import norm

eg1 = loc_Q_tfidf.iloc[0,:]
eg2 = loc_para_tfidf.iloc[0,:]
#print(eg2)

cosine_scor = np.dot(eg1,eg2)/(norm(eg1)*norm(eg2))
print("Cosine Similarity:", cosine_scor)

Cosine Similarity: 0.5128741521314437

In [84]:
# Create function

def compute_cosine(input_1, input_2):
  
  input_1 = input_1#.iloc[0,:]
  input_2 = input_2.iloc[0,:]

  return(np.dot(input_1,input_2)/(norm(input_1)*norm(input_2)))

In [85]:
# Apply function over paragraphs - OVER EACH ROW

cosine_results = loc_para_tfidf.apply(lambda loc_tfidf_row: compute_cosine(loc_tfidf_row, loc_Q_tfidf), axis = 1)
print(cosine_results)

0     0.512874
1     0.000000
2     0.000000
3     0.000000
4     0.000000
5     0.000000
6     0.000000
7     0.000000
8     0.000000
9     0.000000
10    0.000000
11    0.000000
12    0.000000
13    0.000000
14    0.000000
15    0.000000
16    0.000000
17    0.000000
18    0.000000
19    0.331982
dtype: float64

In [86]:
final_ans_full = loc_para_split[cosine_results[cosine_results == max(cosine_results)].index[0]]
print(final_ans_full)

It Jessie Bear's birthday

In [87]:
# Get cosine Similarity
def compute_cosine(input_1, input_2):

  input_1 = input_1#.iloc[0,:]
  input_2 = input_2.iloc[0,:]

  return(np.dot(input_1,input_2)/(norm(input_1)*norm(input_2)))

def get_closest_match_from_Q(loc_para, loc_Q):
  loc_para_split = loc_para.split('. ')

  # TFIDF Section
  
  # Paragraph Transformer
  vectorizer = TfidfVectorizer(smooth_idf=True,use_idf=True)
  vect_result = vectorizer.fit_transform(loc_para_split)
  loc_para_tfidf = pd.DataFrame(vect_result.toarray(), columns=vectorizer.get_feature_names())
  
  # Question Transformer
  vect_result = vectorizer.transform([loc_Q])
  loc_Q_tfidf = pd.DataFrame(vect_result.toarray(), columns=vectorizer.get_feature_names())

  cosine_results = loc_para_tfidf.apply(lambda loc_tfidf_row: compute_cosine(loc_tfidf_row, loc_Q_tfidf), axis = 1)
  final_ans_full = loc_para_split[cosine_results[cosine_results == max(cosine_results)].index[0]]
  return(final_ans_full)

In [ ]:
final_df_Q1.head(5).apply(lambda row: get_closest_match_from_Q(row[0], row[1]), axis = 1)

In [94]:
pip install -U spacy

Requirement already satisfied: spacy in /usr/local/lib/python3.7/dist-packages (3.3.0)
Requirement already satisfied: blis<0.8.0,>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (0.4.1)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.0.2)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy) (3.0.6)
Requirement already satisfied: typer<0.5.0,>=0.3.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (0.4.1)
Requirement already satisfied: thinc<8.1.0,>=8.0.14 in /usr/local/lib/python3.7/dist-packages (from spacy) (8.0.15)
Requirement already satisfied: pathy>=0.3.5 in /usr/local/lib/python3.7/dist-packages (from spacy) (0.6.1)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.9 in /usr/local/lib/python3.7/dist-packages (from spacy) (3.0.9)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from spacy) (57.4.0)
Requirement already satisfied: typing-extensions<4.0.0.0,>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy) (3.10.0.2)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.9.0,>=1.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.8.2)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.4.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.23.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (21.3)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.0.7)
Requirement already satisfied: wasabi<1.1.0,>=0.9.1 in /usr/local/lib/python3.7/dist-packages (from spacy) (0.9.1)
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.21.6)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (3.3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.11.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.0.7)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.0.6)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (4.64.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from catalogue<2.1.0,>=2.0.6->spacy) (3.8.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->spacy) (3.0.8)
Requirement already satisfied: smart-open<6.0.0,>=5.0.0 in /usr/local/lib/python3.7/dist-packages (from pathy>=0.3.5->spacy) (5.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2021.10.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.10)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.7/dist-packages (from typer<0.5.0,>=0.3.0->spacy) (7.1.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->spacy) (2.0.1)

In [ ]:
!python -m spacy download en_core_web_sm
!python -m spacy download en_core_web_lg

In [ ]:
import spacy
nlp = spacy.load('en_core_web_sm')
nlp1 = spacy.load('en_core_web_lg')

In [113]:
def find_NER(input_string):
  text = input_string
  doc = nlp(text)
  for ent in doc.ents:
    print(ent.text, ent.label_)
    return ent.label_

In [114]:
find_NER(final_ans_full)

Jessie Bear's PERSON

'PERSON'

In [98]:
find_NER(final_df_Q1.iloc[0,2]) #Q1_A

Jessie Bear PERSON

In [99]:
find_NER(final_df_Q1.iloc[0,3]) #Q1_B

one CARDINAL

In [101]:
find_NER(final_df_Q1.iloc[0,4]) #Q1_C

In [102]:
find_NER(final_df_Q1.iloc[0,5]) #Q1_D

In [ ]:
def NER_match(input1,input2):
  if(find_NER(input1) == find_NER(input2)):
    print("Answer matched")
  else:
    print("Answer not found")